###
GET http://localhost:3000/daftar_kas
###
GET http://localhost:3000/daftar_warga?filter=%7B%7D&range=%5B0%2C9%5D&sort=%5B%22id%22%2C%22ASC%22%5D
###
GET http://localhost:3000/daftar_warga/60f2725cf8188b304c8302b1
###
POST http://localhost:3000/daftar_kas
content-type: application/json

{
    "no": 1,
    "rincian": "beli nganu Juli",
    "ref": "idk lol",
    "debit": 100000,
    "kredit": 0
}
###
DELETE http://localhost:3000/daftar_warga/60f2729a4feb1c334058ce9b
###
POST http://localhost:8080/register
content-type: application/json

{
    "username" : "username", "password" : "password"
}
###
POST http://localhost:8080/login
content-type: application/json

{
   "username" : "username", "password" : "password"
}